### PR TITLE
fix: Add objDiffer to get new changes to objs

### LINKED ISSUE #111: Implement a Object Diff finder to decide when to re-render
Currently, each `setState()` in the `<PacmanGame />` leads to a re-render. We will be needing more control over when to re-render and when to just update the state but not cause a re-render for:
* Better UX
* Better performance

In future, this can also be used to update component depending on state received from the server.

How to solve: Add a function to find the changes introduced to the state. It should take the `prevState` and `nextState` and return the difference in the key values.

### PR DESCRIPTION
**Pull request by shivangg**
This PR adds function `getObjectDiffs` that will be used to detect what object property in the state has changed and control re-rendering of the component.

The `getObjectDiffs` can also handle **deep diffs** between the objects by using recursive calls. :fire: 

As an example to **showcase the increased control over re-rendering of the component**, I don't rerender in case of when only the pacman direction has changed and everything else stays the same. Previously, it was always re-rendering.

Resolves #111 

stateDiff

### CODE REVIEW

File: client/src/components/PacmanGame/PacmanGame.jsx [hunk 1]
```diff
@@ -43,10 +43,73 @@ class PacmanGame extends Component {
...
+        // eslint-disable-next-line no-console
+        console.log('Diff is', (objDiffs));
+      }
+    };
+
+    const onlyPacmanDirectionChange = objDiffs => (
+      Object.keys(objDiffs).length === 1 && objDiffs.pacman && objDiffs.pacman.direction);
+
+    const onlyGhostMoveCountChange = objDiffs => (
+      Object.keys(objDiffs).length === 1 && objDiffs.moveGhostsCount);
```
Comment (kaushikb11) [inline client/src/components/PacmanGame/PacmanGame.jsx:58]: Why is it necessary for Ghosts?

**Review by kaushikb11 — APPROVED** [review]
LGTM.

File: client/src/components/PacmanGame/PacmanGame.jsx (hunk 1 above)
Comment (shivangg) [reply client/src/components/PacmanGame/PacmanGame.jsx:58]: We don't need to re-render the canvas if **only the moveGhostCount changes.**  This check prevents the re-render in that case.

**Review by nimish-gupta — APPROVED** [review]

**Review by Shalinit3 — APPROVED** [review]
